import React from "react";

const PrivacyPolicy = () => {
  return (
    <div className="container mx-auto px-4 md:px-8 py-8 shadow-lg">
      <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
      <p className="text-sm text-gray-600 mb-6">Last Updated: 2022-11-20</p>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-2">1. Introduction</h2>
        <p className="mb-4">Welcome to Multi Level Boost.</p>
        <p className="mb-4">
          Multi Level Boost (“us”, “we”, or “our”) operates mlb.ng (hereinafter
          referred to as “Service”).
        </p>
        <p className="mb-4">
          Our Privacy Policy governs your visit to mlb.ng, and explains how we
          collect, safeguard and disclose information that results from your use
          of our Service.
        </p>
        <p className="mb-4">
          We use your data to provide and improve Service. By using Service, you
          agree to the collection and use of information in accordance with this
          policy. Unless otherwise defined in this Privacy Policy, the terms
          used in this Privacy Policy have the same meanings as in our Terms of
          Use.
        </p>
        <p>
          Our Terms of Use (“Terms”) govern all use of our Service and together
          with the Privacy Policy constitutes your agreement with us
          (“agreement”).
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-2">2. Definitions</h2>
        <ul className="list-disc ml-6 space-y-2">
          <li>
            <strong>SERVICE</strong> means the mlb.ng website operated by Multi
            Level Boost.
          </li>
          <li>
            <strong>PERSONAL DATA</strong> means data about a living individual
            who can be identified from those data (or from those and other
            information either in our possession or likely to come into our
            possession).
          </li>
          <li>
            <strong>USAGE DATA</strong> is data collected automatically either
            generated by the use of Service or from Service infrastructure
            itself (for example, the duration of a page visit).
          </li>
          <li>
            <strong>COOKIES</strong> are small files stored on your device
            (computer or mobile device).
          </li>
          <li>
            <strong>DATA CONTROLLER</strong> means a natural or legal person who
            (either alone or jointly or in common with other persons) determines
            the purposes for which and the manner in which any personal data
            are, or are to be, processed. For the purpose of this Privacy
            Policy, we are a Data Controller of your data.
          </li>
          <li>
            <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any
            natural or legal person who processes the data on behalf of the Data
            Controller. We may use the services of various Service Providers in
            order to process your data more effectively.
          </li>
          <li>
            <strong>DATA SUBJECT</strong> is any living individual who is the
            subject of Personal Data.
          </li>
          <li>
            <strong>THE USER</strong> is the individual using our Service. The
            User corresponds to the Data Subject, who is the subject of Personal
            Data.
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-2">
          3. Information Collection and Use
        </h2>
        <p>
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-2">4. Types of Data Collected</h2>

        <h3 className="text-xl font-semibold mb-2">Personal Data</h3>
        <p className="mb-4">
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (“Personal Data”). Personally identifiable information
          may include, but is not limited to:
        </p>
        <ul className="list-disc ml-6 space-y-2">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, Country, State, Province, ZIP/Postal code, City</li>
          <li>Cookies and Usage Data</li>
        </ul>

        <p className="mb-4">
          We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials and other information that may be
          of interest to you. You may opt out of receiving any, or all, of these
          communications from us by following the unsubscribe link.
        </p>

        <h3 className="text-xl font-semibold mb-2">Usage Data</h3>
        <p className="mb-4">
          We may also collect information that your browser sends whenever you
          visit our Service or when you access Service by or through any device
          (“Usage Data”).
        </p>
        <p className="mb-4">
          This Usage Data may include information such as your computer’s
          Internet Protocol address (e.g. IP address), browser type, browser
          version, the pages of our Service that you visit, the time and date of
          your visit, the time spent on those pages, unique device identifiers
          and other diagnostic data.
        </p>

        <h3 className="text-xl font-semibold mb-2">Location Data</h3>
        <p className="mb-4">
          We may use and store information about your location if you give us
          permission to do so (“Location Data”). We use this data to provide
          features of our Service, to improve and customize our Service.
        </p>

        <p className="mb-4">
          You can enable or disable location services when you use our Service
          at any time by way of your device settings.
        </p>

        <h3 className="text-xl font-semibold mb-2">Tracking Cookies Data</h3>
        <p className="mb-4">
          We use cookies and similar tracking technologies to track the activity
          on our Service and we hold certain information.
        </p>
        <p className="mb-4">
          Cookies are files with a small amount of data which may include an
          anonymous unique identifier. Cookies are sent to your browser from a
          website and stored on your device. Other tracking technologies are
          also used such as beacons, tags and scripts to collect and track
          information and to improve and analyze our Service.
        </p>
        <p className="mb-4">
          You can instruct your browser to refuse all cookies or to indicate
          when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
        </p>

        <p className="mb-4">Examples of Cookies we use:</p>
        <ul className="list-disc ml-6 space-y-2">
          <li>
            Session Cookies: We use Session Cookies to operate our Service.
          </li>
          <li>
            Preference Cookies: We use Preference Cookies to remember your
            preferences and various settings.
          </li>
          <li>
            Security Cookies: We use Security Cookies for security purposes.
          </li>
          <li>
            Advertising Cookies: Advertising Cookies are used to serve you with
            advertisements that may be relevant to you and your interests.
          </li>
        </ul>
      </section>

      {/* Repeat sections similarly for all other parts of the Privacy Policy */}

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-2">22. Contact Us</h2>
        <p>
          If you have any questions about this Privacy Policy, please contact us
          by email:{" "}
          <a
            href="mailto:support@mlb.com.ng"
            className="text-blue-500 underline"
          >
            support@mlb.com.ng
          </a>
          .
        </p>
      </section>
    </div>
  );
};

export default PrivacyPolicy;
